/*
 * VLibro.java
 *
 * Created on 16-feb-2011, 18:17:07
 */
package gui;

public class VGestionEnfermedades extends javax.swing.JDialog {

    private final VPacientes padre;                                //Enlace a la ventana padre 
    private final aplicacion.FachadaAplicacion fa;                 //Enlace a la fachada de aplicación
    private String cipPaciente;                                    //Paciente actual

    /**
     * Creates new form VLibro
     *
     * @param parent
     * @param modal
     * @param fa
     * @param cipPaciente
     * @param enfermedades
     * @param restoEnfermedades
     */
    //Constructor para un nuevo libro
    public VGestionEnfermedades(java.awt.Dialog parent, boolean modal, aplicacion.FachadaAplicacion fa, String cipPaciente, java.util.List<String> enfermedades, java.util.List<String> restoEnfermedades) {
        //Instanciamos
        super(parent, modal);
        this.fa = fa;
        initComponents();
        padre = (VPacientes) parent;
        this.cipPaciente = cipPaciente;

        //lista de enfermedades no registradas al paciente
        ModeloListaStrings mListaRE = new ModeloListaStrings();
        lstRestoEnfermedades.setModel(mListaRE);
        mListaRE.setElementos(restoEnfermedades);
        if (mListaRE.getSize() > 0) {
            lstRestoEnfermedades.setSelectedIndex(0);
            btnDerecha.setEnabled(true);
        } else {
            btnDerecha.setEnabled(false);
        }

        //crea la lista de enfermedades del paciente
        ModeloListaStrings mListaE = new ModeloListaStrings();
        lstEnfermedadesPadecidas.setModel(mListaE);
        mListaE.setElementos(enfermedades);
        if (mListaE.getSize() > 0) {
            lstEnfermedadesPadecidas.setSelectedIndex(0);
            btnIzquierda.setEnabled(true);
        } else {
            btnIzquierda.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnIzquierda = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstEnfermedadesPadecidas = new javax.swing.JList();
        btnDerecha = new javax.swing.JButton();
        etiquetaRestoEnfermedades = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstRestoEnfermedades = new javax.swing.JList();
        etiquetaEnfermedadesPadecidas = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        etiquetaNombre = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de libros");
        setResizable(false);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel10.setText("GESTIONAR ENFERMEDADES");

        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaI.jpg"))); // NOI18N
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });

        lstEnfermedadesPadecidas.setModel(new ModeloListaStrings());
        jScrollPane3.setViewportView(lstEnfermedadesPadecidas);

        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaD.jpg"))); // NOI18N
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });

        etiquetaRestoEnfermedades.setText("Enfermedades");

        lstRestoEnfermedades.setModel(new ModeloListaStrings());
        jScrollPane2.setViewportView(lstRestoEnfermedades);

        etiquetaEnfermedadesPadecidas.setText("Enfermedades que padece");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        etiquetaNombre.setText("Nombre:");

        textoNombre.setToolTipText("Nombre de usuario");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaRestoEnfermedades, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaEnfermedadesPadecidas))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaRestoEnfermedades)
                            .addComponent(etiquetaEnfermedadesPadecidas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiar)
                        .addComponent(btnActualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón Buscar, filtra las enfermedades en ambas listas
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarEnfermedadesPadecidas(textoNombre.getText());
        buscarEnfermedadesNoPadecidas(textoNombre.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    //Botón Flecha Derecha, asigna una enfermedad al paciente
    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        ModeloListaStrings mRE = (ModeloListaStrings) lstRestoEnfermedades.getModel();
        ModeloListaStrings mE = (ModeloListaStrings) lstEnfermedadesPadecidas.getModel();
        mE.nuevoElemento(mRE.getElementAt(lstRestoEnfermedades.getSelectedIndex()));
        mRE.borrarElemento(lstRestoEnfermedades.getSelectedIndex());
        if (mRE.getSize() == 0) {
            btnDerecha.setEnabled(false);
        } else {
            lstRestoEnfermedades.setSelectedIndex(0);
        }
        lstEnfermedadesPadecidas.setSelectedIndex(mE.getSize() - 1);
        btnIzquierda.setEnabled(true);
    }//GEN-LAST:event_btnDerechaActionPerformed

    //Botón Flecha Izquierda, quita una enfermedad al paciente
    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        ModeloListaStrings mRE = (ModeloListaStrings) lstRestoEnfermedades.getModel();
        ModeloListaStrings mE = (ModeloListaStrings) lstEnfermedadesPadecidas.getModel();
        mRE.nuevoElemento(mE.getElementAt(lstEnfermedadesPadecidas.getSelectedIndex()));
        mE.borrarElemento(lstEnfermedadesPadecidas.getSelectedIndex());
        if (mE.getSize() == 0) {
            btnIzquierda.setEnabled(false);
        } else {
            lstEnfermedadesPadecidas.setSelectedIndex(0);
        }
        lstRestoEnfermedades.setSelectedIndex(mRE.getSize() - 1);
        btnDerecha.setEnabled(true);
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    //Botón Limpiar, pone el campo de texto del nombre a nulo
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        textoNombre.setText(null);
        lstRestoEnfermedades.getModel();
        lstEnfermedadesPadecidas.getModel();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    //Botón Actualizar, guarda correctamente las enfermedades padecidas y no padecidas por el paciente
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        ModeloListaStrings mE = (ModeloListaStrings) lstEnfermedadesPadecidas.getModel();
        fa.actualizarEnfermedadesPaciente(cipPaciente, mE.getElementos());
    }//GEN-LAST:event_btnActualizarActionPerformed

    //Botón Regresar, vuelve a la ventana anterior, cerrando la ventana actual
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        padre.buscarPacientes();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel etiquetaEnfermedadesPadecidas;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaRestoEnfermedades;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lstEnfermedadesPadecidas;
    private javax.swing.JList lstRestoEnfermedades;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables

    //busca las enfermedades no padecidas en la lista
    public void buscarEnfermedadesNoPadecidas(String enfermedad) {
        java.util.List<String> enfermedadesNoPadecidas;
        ModeloListaStrings mListaRE = new ModeloListaStrings();
        lstEnfermedadesPadecidas.setModel(mListaRE);
        enfermedadesNoPadecidas = fa.obtenerEnfermedadesNoPadecidas(cipPaciente, enfermedad);
        java.util.ArrayList<String> nombres = new java.util.ArrayList<>();
        for (int i = 0; i < enfermedadesNoPadecidas.size(); i++) {
            nombres.add(enfermedadesNoPadecidas.get(i));
        }
        mListaRE.setElementos(nombres);
        if (mListaRE.getSize() > 0) {
            //selecciona el primer elemento de la lista automáticamente
            lstEnfermedadesPadecidas.setSelectedIndex(0);
            //activa el botón de Eliminar
            btnIzquierda.setEnabled(true);
        } else {
            btnIzquierda.setEnabled(false);
        }
    }

    //busca las enfermedades no padecidas en la lista
    public void buscarEnfermedadesPadecidas(String enfermedad) {
        java.util.List<String> enfermedadesPadecidas;
        ModeloListaStrings mListaE = new ModeloListaStrings();
        lstEnfermedadesPadecidas.setModel(mListaE);
        enfermedadesPadecidas = fa.obtenerEnfermedadesPadecidas(cipPaciente, enfermedad);
        java.util.ArrayList<String> nombres = new java.util.ArrayList<>();
        for (int i = 0; i < enfermedadesPadecidas.size(); i++) {
            nombres.add(enfermedadesPadecidas.get(i));
        }
        mListaE.setElementos(nombres);
        if (mListaE.getSize() > 0) {
            //selecciona el primer elemento de la lista automáticamente
            lstEnfermedadesPadecidas.setSelectedIndex(0);
            //activa el botón de Eliminar
            btnIzquierda.setEnabled(true);
        } else {
            btnIzquierda.setEnabled(false);
        }
    }
}
