package gui;

import aplicacion.Ejemplar;

/**
 *
 * @author alumno
 */
public class VPrestamo extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    private final VLibro padre;
    private final Ejemplar ejemplar;
    private final Integer libro;

    /**
     * Creates new form VPrincipal
     *
     * @param parent
     * @param modal
     * @param fa
     * @param idLibro
     * @param ejemplar
     */
    //Constructor
    public VPrestamo(java.awt.Dialog parent, boolean modal, aplicacion.FachadaAplicacion fa, Integer idLibro, Ejemplar ejemplar) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        this.libro = idLibro;
        padre = (VLibro) parent;
        this.ejemplar = ejemplar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscaNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPrestamos = new javax.swing.JTable();
        btnNuevoPrestamo = new javax.swing.JButton();
        etiquetaTitulo = new javax.swing.JLabel();
        buscaId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Préstamos");
        setName("vPrincipal"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buscaNombre.setToolTipText("Titulo a buscar");

        jLabel3.setText("Id:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaPrestamos.setAutoCreateRowSorter(true);
        tablaPrestamos.setModel(new ModeloTablaPrestamos());
        tablaPrestamos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaPrestamos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaPrestamos);
        tablaPrestamos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnNuevoPrestamo.setText("Prestar");
        btnNuevoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPrestamoActionPerformed(evt);
            }
        });

        etiquetaTitulo.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(637, 637, 637)
                            .addComponent(btnBuscar))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(etiquetaTitulo)
                            .addGap(18, 18, 18)
                            .addComponent(buscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buscaId, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnNuevoPrestamo)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTitulo)
                    .addComponent(buscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buscaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevoPrestamo)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel4.setText("GESTIONAR PRESTAMOS");

        btnSalir.setText("Regresar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Gestión préstamos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Función llamada al hacer click sobre el botón de buscar. Permite buscar usuarios para el préstamo
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //Buscamos a los usuarios
        buscarPrestamos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    //Permite prestar el ejemplar
    private void btnNuevoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPrestamoActionPerformed
        //Creamos el modelo de tabla préstamos
        ModeloTablaPrestamos m;
        m = (ModeloTablaPrestamos) tablaPrestamos.getModel();
        //Si el usuario seleccionado tiene préstamos vencidos
        if ((Integer) m.getValueAt(tablaPrestamos.getSelectedRow(), 3) > 0) {
            //No se le permite llevar el ejemplar prestado.
            //Salta la excepción y se muestra en la ventana
            fa.muestraExcepcion("No se puede prestar el ejemplar. El usuario seleccionado tiene préstamos vencidos.");
            //Regresamos
            return;
        }
        //En otro caso le prestamos el ejemplar
        ejemplar.setUsuario((String) m.getValueAt(tablaPrestamos.getSelectedRow(), 0));
        fa.nuevoPrestamo(libro, ejemplar);
        //Actualizamos la tabla de ejemplares
        padre.actualizarTablaEjemplares();
        //Una vez prestado destruimos la ventana
        this.dispose();
    }//GEN-LAST:event_btnNuevoPrestamoActionPerformed

    //Permite salir de la ventana
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Destruimos esta ventana
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void buscarPrestamos() {
        //Creamos el modelo de tabla préstamos
        ModeloTablaPrestamos m;
        m = (ModeloTablaPrestamos) tablaPrestamos.getModel();
        //Se buscan los usuarios que cumplen el criterio de búsqueda y se menten en la tabla
        m.setFilas(fa.consultarPUsuarios((buscaId.getText().isEmpty()) ? null : buscaId.getText(), buscaNombre.getText()));
        //Si hay alguno se selecciona el primero
        if (m.getRowCount() > 0) {
            tablaPrestamos.setRowSelectionInterval(0, 0);
        }
        //De no haberlo se regresa sin hacer nada.
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNuevoPrestamo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField buscaId;
    private javax.swing.JTextField buscaNombre;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPrestamos;
    // End of variables declaration//GEN-END:variables

}
