package gui.ventanas;

import gui.modelos.ModeloTablaHospitales;
import aplicacion.clases.Cita;

public class VDerivarHospital extends javax.swing.JDialog {

    private VPrincipal padre;                                //Enlace a la ventana padre 
    private aplicacion.FachadaAplicacion fa;                 //Enlace a la fachada de aplicación
    private Cita cita;                                       //Cita

    /**
     *
     * @param parent
     * @param modal
     * @param fa
     * @param cita
     */
    public VDerivarHospital(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Cita cita) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        padre = (VPrincipal) parent;
        this.cita = cita;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaCodigo = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        textoProvincia = new javax.swing.JTextField();
        etiquetaProvincia = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        etiquetaCodigo1 = new javax.swing.JLabel();
        textoDistancia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHospitales = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Derivar al hospital");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        etiquetaCodigo.setText("Código:");

        textoCodigo.setToolTipText("Código del hospital");

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Busca los hospitales");
        btnBuscar.setActionCommand("Actualizar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        textoProvincia.setToolTipText("Provincia del hospital");

        etiquetaProvincia.setText("Provincia:");

        etiquetaNombre.setText("Nombre:");

        textoNombre.setToolTipText("Nombre del hospital");

        etiquetaCodigo1.setText("Distancia:");

        textoDistancia.setToolTipText("Distancia al hospital");

        tablaHospitales.setModel(new ModeloTablaHospitales());
        tablaHospitales.setToolTipText("Tabla de hospitales");
        tablaHospitales.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaHospitales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaHospitalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaHospitales);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(etiquetaProvincia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etiquetaCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaCodigo1)
                    .addComponent(etiquetaNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoDistancia, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCodigo)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiquetaProvincia)
                        .addComponent(textoDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiquetaCodigo1)
                        .addComponent(btnBuscar))
                    .addComponent(textoProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRegresar.setText("Regresar");
        btnRegresar.setToolTipText("Vuelve a la ventana anterior");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.setToolTipText("Confirma derivar el paciente al hospital");
        btnConfirmar.setEnabled(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnConfirmar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //botón de Confirmar, confirma derivar un paciente al hospital
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed

        //Comprobamos que esta seleccionada una fila
        int index = tablaHospitales.getSelectedRow();
        if (index >= 0) {

            //Obtenemos tabla
            ModeloTablaHospitales th = (ModeloTablaHospitales) tablaHospitales.getModel();

            //Derivamos
            fa.derivarHospital(th.obtenerHospital(index), cita);

            //Cerramos
            this.dispose();
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    //botón de Regresar, vuelve a la ventana anterior
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        this.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        //Obtenemos valores
        Integer codigo;
        Float distancia;
        try {
            codigo = Integer.parseInt(textoCodigo.getText());
        } catch (Exception e) {
            codigo = null;
        }
        try {
            distancia = Float.parseFloat(textoDistancia.getText());
        } catch (Exception e) {
            distancia = null;
        }

        //Obtenemos tabla
        ModeloTablaHospitales th = (ModeloTablaHospitales) tablaHospitales.getModel();

        //Insertamos valores
        th.setFilas(fa.consultarHospitalAsociado(cita.getAmbulatorio(),
                textoNombre.getText(),
                textoProvincia.getText(),
                codigo,
                distancia));
        
        if (th.getRowCount() > 0) {
            tablaHospitales.setRowSelectionInterval(0, 0);
            btnConfirmar.setEnabled(true);
        textoNombre.setText(th.obtenerHospital(tablaHospitales.getSelectedRow()).getNombre());
        textoCodigo.setText(th.obtenerHospital(tablaHospitales.getSelectedRow()).getCodigo().toString());
        textoDistancia.setText(th.obtenerHospital(tablaHospitales.getSelectedRow()).getDistancia().toString());
        textoProvincia.setText(th.obtenerHospital(tablaHospitales.getSelectedRow()).getProvincia());
        } else {
            btnConfirmar.setEnabled(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaHospitalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHospitalesMouseClicked
        //Creamos el modelo de tabla hospitales
        ModeloTablaHospitales m = (ModeloTablaHospitales) tablaHospitales.getModel();
        //Obtenemos todos los datos del hospital (fila) en el que se hizo click y los metemos en los campos
        textoNombre.setText(m.obtenerHospital(tablaHospitales.getSelectedRow()).getNombre());
        textoCodigo.setText(m.obtenerHospital(tablaHospitales.getSelectedRow()).getCodigo().toString());
        textoDistancia.setText(m.obtenerHospital(tablaHospitales.getSelectedRow()).getDistancia().toString());
        textoProvincia.setText(m.obtenerHospital(tablaHospitales.getSelectedRow()).getProvincia());
    }//GEN-LAST:event_tablaHospitalesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel etiquetaCodigo;
    private javax.swing.JLabel etiquetaCodigo1;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaProvincia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHospitales;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoDistancia;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoProvincia;
    // End of variables declaration//GEN-END:variables
}
