package gui.ventanas;

import gui.modelos.ModeloTablaPersonal;
import gui.modelos.ModeloTablaPacientes;
import aplicacion.clases.PersonalSanitario;

public class VPersonal extends javax.swing.JDialog {

    private final VPrincipal padre;                           //Enlace a la ventana padre
    private final aplicacion.FachadaAplicacion fa;            //Enlace a la fachada de aplicación
    private final Integer ambulatorio;                        //Ambulatorio

    /**
     * Creates new form VPersonal
     *
     * @param parent
     * @param modal
     * @param fa
     */
    //Constructor de la ventana
    public VPersonal(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Integer ambulatorio) {
        super(parent, modal);
        this.fa = fa;
        initComponents();
        padre = (VPrincipal) parent;
        this.ambulatorio = ambulatorio;

        btnCitas.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnEspecialidades = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPersonal = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        etiquetaNombre = new javax.swing.JLabel();
        textoDNI = new javax.swing.JTextField();
        etiquetaDNI = new javax.swing.JLabel();
        textoFechaIncorporacion = new javax.swing.JTextField();
        etiquetaFechaIncorporacion = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        etiquetaClase = new javax.swing.JLabel();
        textoClase = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        etiquetaTelefono = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JTextField();
        etiquetaAntiguedad = new javax.swing.JLabel();
        textoAntiguedad = new javax.swing.JTextField();
        etiquetaSueldo = new javax.swing.JLabel();
        textoSueldo = new javax.swing.JTextField();
        etiquetaContrasena = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JToggleButton();
        btnSanitario = new javax.swing.JToggleButton();
        textoContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personal");
        setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("Pone en blanco los cuadros de texto, así como limpia la tabla");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);

        btnRegresar.setText("Regresar");
        btnRegresar.setToolTipText("Vuelve a la ventana anterior");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnEspecialidades.setText("Especialidades");
        btnEspecialidades.setEnabled(false);

        btnCitas.setText("Citas");
        btnCitas.setToolTipText("Abre la ventana de citas");
        btnCitas.setEnabled(false);
        btnCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCitasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(49, 49, 49)
                .addComponent(btnCitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEspecialidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRegresar)
                        .addComponent(btnCitas))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaPersonal.setModel(new ModeloTablaPersonal());
        tablaPersonal.setToolTipText("Tabla de trabajadores");
        tablaPersonal.setAutoscrolls(false);
        tablaPersonal.getTableHeader().setReorderingAllowed(false);
        tablaPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPersonalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPersonal);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        etiquetaNombre.setText("Nombre:");

        textoDNI.setToolTipText("DNI del trabajador");

        etiquetaDNI.setText("DNI:");

        textoFechaIncorporacion.setToolTipText("Fecha de incorporación del trabajador");

        etiquetaFechaIncorporacion.setText("Fecha Incorporación:");

        textoNombre.setToolTipText("Nombre del trabajador");

        etiquetaClase.setText("Clase:");

        textoClase.setToolTipText("Clase del trabajador");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        etiquetaTelefono.setText("Tel:");

        textoTelefono.setToolTipText("Teléfono del trabajador");

        etiquetaAntiguedad.setText("Antigüedad:");

        textoAntiguedad.setToolTipText("Antigüedad en el puesto del trabajador");

        etiquetaSueldo.setText("Sueldo:");

        textoSueldo.setToolTipText("Sueldo del trabajador");

        etiquetaContrasena.setText("Contraseña:");

        btnAdmin.setText("Admin");
        btnAdmin.setToolTipText("Indica si el personal es administrador");
        btnAdmin.setEnabled(false);

        btnSanitario.setText("Sanitario");
        btnSanitario.setToolTipText("Indica si el personal es sanitario");

        textoContrasena.setToolTipText("Contraseña del administrador");
        textoContrasena.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(etiquetaDNI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(etiquetaTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(etiquetaNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSanitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(etiquetaClase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoClase, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(etiquetaContrasena)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoContrasena))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(etiquetaFechaIncorporacion)
                                .addGap(12, 12, 12)
                                .addComponent(textoFechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(etiquetaAntiguedad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(etiquetaSueldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiquetaNombre))
                    .addComponent(btnAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaDNI)
                    .addComponent(etiquetaTelefono)
                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSanitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaFechaIncorporacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaClase)
                    .addComponent(textoClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaContrasena)
                    .addComponent(btnBuscar)
                    .addComponent(textoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Función que permite salir de la ventana de personal
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        //Buscamos ambulatorios
        padre.buscarAmbulatorios();
        //Y destruimos esta ventana
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    //Botón Limpiar, pone todos los campos de texto en blanco
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //Creamos el modelo de tabla personal
        ModeloTablaPersonal m = (ModeloTablaPersonal) tablaPersonal.getModel();
        //Metemos un array vacío como las filas
        m.setFilas(new java.util.ArrayList<>());
        textoAntiguedad.setText(null);
        textoClase.setText(null);
        textoContrasena.setText(null);
        textoFechaIncorporacion.setText(null);
        textoNombre.setText(null);
        textoDNI.setText(null);
        textoTelefono.setText(null);
        textoSueldo.setText(null);
        //Deshabilitamos el botón de Citas
        btnCitas.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    //Botón Buscar, busca el personal del ambulatorio
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarPersonal();
    }//GEN-LAST:event_btnBuscarActionPerformed

    //Función que permite recoger los datos de un trabajador con un click en la tabla de personal
    private void tablaPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPersonalMouseClicked
        //Creamos el modelo de tabla personal
        ModeloTablaPersonal m = (ModeloTablaPersonal) tablaPersonal.getModel();
        //Obtenemos todos los datos del trabajador (fila) en el que se hizo click y los metemos en los campos
        textoDNI.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getDNI());
        textoNombre.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getNombre());
        textoAntiguedad.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getAntiguedad());
        textoClase.setText(tablaPersonal.getValueAt(tablaPersonal.getSelectedRow(), 3).toString());
        textoFechaIncorporacion.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getFechaIncorporacion().toString());
        textoTelefono.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getTelefono());
        textoSueldo.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getSueldo().toString());
        btnCitas.setEnabled(true);
    }//GEN-LAST:event_tablaPersonalMouseClicked

    //Botón Citas, abre la ventana de citas del médico
    private void btnCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCitasActionPerformed

        int index = tablaPersonal.getSelectedRow();
        if (index >= 0) {
            fa.nuevaVCitasPendientes(this, ((ModeloTablaPersonal) tablaPersonal.getModel()).obtenerPersonal(index));
        }

    }//GEN-LAST:event_btnCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JToggleButton btnAdmin;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEspecialidades;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JToggleButton btnSanitario;
    private javax.swing.JLabel etiquetaAntiguedad;
    private javax.swing.JLabel etiquetaClase;
    private javax.swing.JLabel etiquetaContrasena;
    private javax.swing.JLabel etiquetaDNI;
    private javax.swing.JLabel etiquetaFechaIncorporacion;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaSueldo;
    private javax.swing.JLabel etiquetaTelefono;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaPersonal;
    private javax.swing.JTextField textoAntiguedad;
    private javax.swing.JTextField textoClase;
    private javax.swing.JPasswordField textoContrasena;
    private javax.swing.JTextField textoDNI;
    private javax.swing.JTextField textoFechaIncorporacion;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoSueldo;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables

    //Función que permite buscar un trabajador en la base de datos
    public void buscarPersonal() {
        //Creamos el modelo de tabla personal
        ModeloTablaPersonal m = (ModeloTablaPersonal) tablaPersonal.getModel();
        m.setFilas(fa.consultarPersonal(textoDNI.getText(), textoNombre.getText(), ambulatorio));
        //Si hay coincidencias
        if (m.getRowCount() > 0) {
            //Seleccionamos la primera
            tablaPersonal.setRowSelectionInterval(0, 0);
            //Autocompletamos con los datos seleccionados
            textoDNI.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getDNI());
            textoNombre.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getNombre());
            textoAntiguedad.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getAntiguedad());
            textoClase.setText(tablaPersonal.getValueAt(tablaPersonal.getSelectedRow(), 3).toString());
            textoFechaIncorporacion.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getFechaIncorporacion().toString());
            textoTelefono.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getTelefono());
            textoSueldo.setText(m.obtenerPersonal(tablaPersonal.getSelectedRow()).getSueldo().toString());
            //Habilitamos el botón de citas
            btnCitas.setEnabled(true);
        } else {
            //De no haberlas, deshabilitamos el botón de citas
            btnCitas.setEnabled(false);
        }
    }
}
